[versions]
java = "17"
agp = "8.5.0"
kotlin = "2.0.0"
androidGradlePlugin = "8.2.2"
core-ktx = "1.13.1"
junit = "4.13.2"
androidx-test = "1.6.1"
androidx-test-ext-junit = "1.2.1"
android-lifecycle = "2.8.3"
activity-compose = "1.9.0"
compose-bom = "2024.06.00"
compose-navigation = "2.7.7"
detekt = "1.23.6"
detektCompose = "0.4.5"
grpc = "1.57.0"
hilt = "2.51.1"
retrofit = "2.9.0"
kotlinxSerializationJson = "1.7.0"
ksp = "2.0.0-1.0.22"
paparazzi = "1.3.2"

#SDK
minSdk = "26"
compileSdk = "34"
targetSdk = "34"

[libraries]
#ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "android-lifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "android-lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "android-lifecycle" }

#Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material3 = { group = "androidx.compose.material3", name = "material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }

#Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

#Network
grpc-okhttp = { group = "io.grpc", name = "grpc-okhttp", version.ref = "grpc" }
grpc-protobuf-lite = { group = "io.grpc", name = "grpc-protobuf-lite", version.ref = "grpc" }
protobuf-lite = { group = "com.google.protobuf", name = "protobuf-lite", version = "3.23.0" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

#Test
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
google-truth = { group = "com.google.truth", name = "truth", version = "1.4.2" }
androidx-test-archcore = { group = "androidx.arch.core", name = "core-testing", version = "2.2.0" }
turbine = { group = "app.cash.turbine", name = "turbine", version = "1.1.0" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version = "5.2.1" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version = "1.8.1" }
androidx-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidx-test" }
paparazzi = { group = "app.cash.paparazzi", name = "paparazzi-gradle-plugin", version.ref = "paparazzi" }

#BuildLogic
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }

#CodeStyle
detektFormat = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detektCompose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detektCompose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
cash-paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

#Convention Plugins
start-android-application = { id = "start.android.application", version = "unspecified" }
start-android-hilt = { id = "start.android.hilt", version = "unspecified" }
start-android-library = { id = "start.android.library", version = "unspecified" }
start-android-library-compose = { id = "start.android.library.compose", version = "unspecified" }
start-jvm-library = { id = "start.jvm.library", version = "unspecified" }
